sudo: required
services:
    - docker


before_install:
    - docker build -t pushp132129/vision-test -f ./client/Dockerfile.dev ./client
    - npm audit --json >> $/vision/report.json || true


script:
    - docker run pushp132129/vision-test npm test -- --coverage

#Pushing images to the DockerHub
after_success:
    - docker build -t pushp132129/vision-client ./client
    - docker build -t pushp132129/vision-nginx ./nginx
    - docker build -t pushp132129/vision-server ./server
    - docker build -t pushp132129/vision-worker ./worker
    
#Logging into the Docker CLI

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#Pushing the images to the DockerHub
    - docker push pushp132129/vision-client
    - docker push pushp132129/vision-nginx
    - docker push pushp132129/vision-server
    - docker push pushp132129/vision-worker